joints:
  name:
    - torso_lift_joint
    - head_tilt_joint
    - l_gripper_joint
    - r_gripper_joint
    - r_upper_arm_roll_joint
    - r_shoulder_pan_joint
    - r_shoulder_lift_joint
    - r_forearm_roll_joint
    - r_elbow_flex_joint
    - r_wrist_flex_joint
    - r_wrist_roll_joint
    - l_upper_arm_roll_joint
    - l_shoulder_pan_joint
    - l_shoulder_lift_joint
    - l_forearm_roll_joint
    - l_elbow_flex_joint
    - l_wrist_flex_joint
    - l_wrist_roll_joint
  position:
    - 0.31
    - 1.05
    - 0.01 
    - 0.01
    - -1.32
    - -1.08
    - 0.16
    - 0.0
    - -1.14
    - -1.05
    - 1.57
    - 1.32
    - 1.08
    - 0.16
    - 0.0
    - -1.14
    - -1.05
    - 1.57
